// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnp3T1CbcMuWy5-CcqGHJE_zp0_HnGQMk',
    appId: '1:850995181107:web:fba5aecb24591c3dbd9546',
    messagingSenderId: '850995181107',
    projectId: 'gdscproject-1407f',
    authDomain: 'gdscproject-1407f.firebaseapp.com',
    databaseURL: 'https://gdscproject-1407f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gdscproject-1407f.appspot.com',
    measurementId: 'G-PHR7T6QRE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJwwr3iP_IY6R4kLbisz7vqF7Tu8MS3c',
    appId: '1:850995181107:android:2fb636946f7faea0bd9546',
    messagingSenderId: '850995181107',
    projectId: 'gdscproject-1407f',
    databaseURL: 'https://gdscproject-1407f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gdscproject-1407f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-lu8O_XRz-9ZMy_b6Sr9bEl-XR-j6Q1k',
    appId: '1:850995181107:ios:7c6d112a1e8faed0bd9546',
    messagingSenderId: '850995181107',
    projectId: 'gdscproject-1407f',
    databaseURL: 'https://gdscproject-1407f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gdscproject-1407f.appspot.com',
    androidClientId: '850995181107-s4ea086ubldtl1srj7uumn5jbfcla3cd.apps.googleusercontent.com',
    iosClientId: '850995181107-361e5keq3h6pavokfjg707ndd8nu3qnv.apps.googleusercontent.com',
    iosBundleId: 'com.alitas.newproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-lu8O_XRz-9ZMy_b6Sr9bEl-XR-j6Q1k',
    appId: '1:850995181107:ios:18c78276efc9dcd1bd9546',
    messagingSenderId: '850995181107',
    projectId: 'gdscproject-1407f',
    databaseURL: 'https://gdscproject-1407f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gdscproject-1407f.appspot.com',
    androidClientId: '850995181107-s4ea086ubldtl1srj7uumn5jbfcla3cd.apps.googleusercontent.com',
    iosClientId: '850995181107-4bh4apj2caupuu1fqt6pm4e4tssd8kn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.newproj',
  );
}
